### ISSUE TITLE
Migrate ITS_LIVE data to AWS OpenData

### ISSUE THREAD

**Issue by jhkennedy** [ASFHyP3/OpenData#1]
To make the ITS_LIVE data available on AWS we'll need to follow the AWS Open Data Sponsorship Program's [Onboarding Handbook for Data Providers](https://assets.opendata.aws/aws-onboarding-handbook-for-data-providers-en-US.pdf)

That, at the high level, will look like:
```[tasklist]
### Onboarding Steps
- [x] Applying to the AWS Open Data Sponsorship Program
- [x] Providing Documentation, tutorial(s), & Registry of Open Data entry
- [x] ASF Director accepting the AWS Open Data Sponsorship Program Terms and Conditions
- [ ] https://github.com/ASFHyP3/OpenData/issues/4
- [ ] https://github.com/ASFHyP3/OpenData/issues/10
- [x] Launching your dataset
```

@alex-s-gardner, @markf6, @mliukis, @betolink lets use this issue, and any child issues, to organize this effort.

**Comment by jhkennedy** [comment]
Draft PR for the AWS OpenData catalog entry detailing documentation/tutorials is open:
https://github.com/awslabs/open-data-registry/pull/2071

Once we've migrated the data and are "ready to launch," we'll take the PR out of the draft, and the AWS team will do a final review. Merging will launch the dataset on AWS OpenData.

**Comment by betolink** [comment]
@jhkennedy what are the tasks on the providing documentation, tutorial(s)? I think the notebooks we have + Emma's book could count as tutorials, although I'm not sure if we have extensive documentation of the Zarr cubes.

**Comment by jhkennedy** [comment]
@betolink In terms of the AWS OpenData catalog entry (dataset landing page), I believe we already have a pretty extensive set of tools/tutorials listed, including Emma's, in [the catalog PR](https://github.com/awslabs/open-data-registry/pull/2071):

https://github.com/awslabs/open-data-registry/pull/2071/files#diff-b6e4e7861ef29c2ac0b2c0e1aed71dfaf434d200ad0bf508d964944d2c384ab3R46-R81

I think the only thing we're missing is a description of *the AWS Bucket* -- the prefixes, the data inside, etc. I've started on a README in #8, which would have that, and be a top-level README in the bucket.

**Comment by jhkennedy** [comment]
ITS_LIVE IS LIVE!

https://registry.opendata.aws/its-live-data/
